
---
- hosts: remote
  become: true
  become_user: root
  tasks:
  - name: Verify any application are running or not
    shell: if ps -eaf | egrep 'httpd' | grep -v grep > /dev/null; then echo 'process_running'; else echo 'process_not_running'; fi
    ignore_errors: true
    register: app_proc_check

  - debug:
     msg="{{ app_proc_check.stdout }}"

  - name: Decision point to start patching
    fail:
     msg="{{ inventory_hostname }} having running applications, Please stop first and then attempt patching."
    when: app_proc_check.stdout == "process_running"

  - name: Current Kernel Version
    shell: uname -r
    register: curr_kernel

  - name:  Upgrade kernel package on CentOS server
    yum:
     name="kernel"
     state=latest
    when: app_proc_check.stdout == "process_not_running" and ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
    register: yum_update

  - debug: msg="Kernel has been updated."
    when: yum_update.rc == 0

  - name: Check if reboot required after kernel update on CentOS
    shell: kernel_new=$(rpm -q --last kernel | head -1 | awk '{print $1}' | sed 's/kernel-//'); kernel_now=$(uname -r); if [[ $kernel_new != $kernel_now ]]; then echo "reboot is required";else echo "reboot is not required"; fi
    ignore_errors: true
    register: reboot_check

  - debug: msg="{{ reboot_check.stdout}}"

  - name: Reboot the system after patching
    shell: "shutdown -r y now"
    async: 1
    poll: 0
    #when:  reboot_check.stdout == "reboot is required"
    #register: reboot_started

  - name: Wait the system to come up
    pause:
        minutes: 1

  - name: New kernel version
    shell: uname -r
    register: new_ker

  - debug: msg="New Kernel Version is {{ new_ker.stdout }} and old kernel version was {{ curr_kernel.stdout }}"

