---
- hosts: remote
  become: true
  become_user: root
  tasks:
  - name: Verify any application are running or not
    shell: if ps -eaf | egrep 'httpd' | grep -v grep > /dev/null; then echo 'process_running'; else echo 'process_not_running'; fi
    ignore_errors: true
    register: app_proc_check

  - debug:
     msg="{{ app_proc_check.stdout }}"

  - name: Decision point to start patching
    fail:
     msg="{{ inventory_hostname }} having running applications, Please stop first and then attempt patching."
    when: app_proc_check.stdout == "process_running"

  - name: Current Kernel Version
    shell: uname -r
    register: curr_kernel

  - name:  Upgrade kernel package on CentOS server
    yum:
     name="kernel"
     state=latest
    when: app_process_check.stdout == "process_not_running" and ansible_distribution == 'CentOS'
    register: yum_update

  - debug: msg="Kernel has been updated."
    when: yum_update.rc == 0

